package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/tompscanlan/labreserved/client/operations"
)

// Default labreserved HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new labreserved HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Labreserved {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost", "/", []string{"http", "https"})
	return New(transport, formats)
}

// New creates a new labreserved client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Labreserved {
	cli := new(Labreserved)
	cli.Transport = transport

	cli.Operations = operations.New(transport, formats)

	return cli
}

// Labreserved is a client for labreserved
type Labreserved struct {
	Operations *operations.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Labreserved) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Operations.SetTransport(transport)

}
