sudo: false
services:
  - docker
language: go
go:
  - 1.6.3
install:
  - go get -t -v ./...
  - npm install --save-dev frisby
  - npm install -g jasmine-node
before_script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
script:
  - CGO_ENABLED=0 go build -a -installsuffix cgo ./cmd/labreserved-server/
  - file labreserved-server
  - ldd labreserved-server || true
  - sh -x ./scripts/make-cert.sh
  - docker build -t tompscanlan/labreserved --rm=true .
  - docker run -d -p2080:80 -p20443:443 -e TEAM_ID=7357 --name labd tompscanlan/labreserved
  - jasmine-node frisbyjs/
  - docker logs labd
after_sucess:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push tompscanlan/labreserved
