sudo: false
services:
  - docker
language: go
go:
  - 1.6.3
install:
  - npm install --save-dev frisby
  - npm install -g jasmine-node
before_script:
  - make deps
  - make valid
script:
  - make docker
  - make run
  - jasmine-node frisbyjs/
  - docker logs labd
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag tompscanlan/labreserved tompscanlan/labreserved:${TRAVIS_BRANCH}
  - docker push tompscanlan/labreserved:latest
  - docker push tompscanlan/labreserved:${TRAVIS_BRANCH}
