sudo: false
services:
  - docker
language: go
go:
  - 1.6.3
script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
  - go build ./cmd/labreserved-server/
  - sh -x ./scripts/make-cert.sh
  - docker build -t tompscanlan/labreserved --rm=true .
  - docker run -d -p2080:80 -p20443:443 -e BLOB_ID=7357 tompscanlan/labreserved
  - curl --request GET   --url http://127.0.0.1:2080/items   --header 'content-type: application/json'
  - curl -k --request GET   --url https://127.0.0.1:20443/items   --header 'content-type: application/json'
