sudo: false
services:
  - docker
language: go
go:
  - 1.4.2
  - 1.6.3
  - 1.7
  - tip
matrix:
  include:
    - go: 1.4.2
      script:
        - go get -t -v ./...
        - go test -v -race ./...
  allow_failures:
    - go: 1.4.2
    - go: tip
  fast_finish: true
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...

