sudo: false
services:
  - docker
language: go
go:
  - 1.6.3
install:
  - go get -t -v ./...
before_script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
script:
  - go build ./cmd/labreserved-server/
  - sh -x ./scripts/make-cert.sh
  - docker build -t tompscanlan/labreserved --rm=true .
  - docker run -d -p2080:80 -p20443:443 -e BLOB_ID=7357 tompscanlan/labreserved
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push tompscanlan/labreserved
