sudo: false
services:
  - docker
language: go
go:
  - 1.6.3
matrix:
  include:
    - go: 1.7
      script:
        - go get -t -v ./...
        - go test -v -race ./...
    - go: tip
      script:
        - go get -t -v ./...
        - go test -v -race ./...
  allow_failures:
    - go: 1.7
    - go: tip
  fast_finish: true
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
  - sh -x ./scripts/make-cert.sh
  - docker build -t tompscanlan/labreserved --rm=true .
  - docker run -d -p2080:80 -p20443:443 -e BLOB_ID=7357 tompscanlan/labreserved
  - curl --request GET   --url http://127.0.0.1:2080/items   --header 'content-type: application/json'
  - curl -k --request GET   --url https://127.0.0.1:20443/items   --header 'content-type: application/json'
