package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/tompscanlan/labreserved/models"
)

/*GetItemNameOK get specific lab item

swagger:response getItemNameOK
*/
type GetItemNameOK struct {

	// In: body
	Payload *models.Item `json:"body,omitempty"`
}

// NewGetItemNameOK creates GetItemNameOK with default headers values
func NewGetItemNameOK() *GetItemNameOK {
	return &GetItemNameOK{}
}

// WithPayload adds the payload to the get item name o k response
func (o *GetItemNameOK) WithPayload(payload *models.Item) *GetItemNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get item name o k response
func (o *GetItemNameOK) SetPayload(payload *models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
