package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetItemNameParams creates a new GetItemNameParams object
// with the default values initialized.
func NewGetItemNameParams() GetItemNameParams {
	var ()
	return GetItemNameParams{}
}

// GetItemNameParams contains all the bound params for the get item name operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetItemName
type GetItemNameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*name of the lab equipment
	  Required: true
	  Max Length: 512
	  Min Length: 1
	  In: path
	*/
	Name string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetItemNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rName, rhkName, _ := route.Params.GetOK("name")
	if err := o.bindName(rName, rhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetItemNameParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Name = raw

	if err := o.validateName(formats); err != nil {
		return err
	}

	return nil
}

func (o *GetItemNameParams) validateName(formats strfmt.Registry) error {

	if err := validate.MinLength("name", "path", string(o.Name), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "path", string(o.Name), 512); err != nil {
		return err
	}

	return nil
}
