package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/tompscanlan/labreserved/models"
)

/*GetItemsOK list all items in the lab

swagger:response getItemsOK
*/
type GetItemsOK struct {

	// In: body
	Payload models.Items `json:"body,omitempty"`
}

// NewGetItemsOK creates GetItemsOK with default headers values
func NewGetItemsOK() *GetItemsOK {
	return &GetItemsOK{}
}

// WithPayload adds the payload to the get items o k response
func (o *GetItemsOK) WithPayload(payload models.Items) *GetItemsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get items o k response
func (o *GetItemsOK) SetPayload(payload models.Items) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
