package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/tompscanlan/labreserved/models"
)

// NewPostItemNameReservationParams creates a new PostItemNameReservationParams object
// with the default values initialized.
func NewPostItemNameReservationParams() PostItemNameReservationParams {
	var ()
	return PostItemNameReservationParams{}
}

// PostItemNameReservationParams contains all the bound params for the post item name reservation operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostItemNameReservation
type PostItemNameReservationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*name of the lab equipment
	  Required: true
	  Max Length: 512
	  Min Length: 1
	  In: path
	*/
	Name string
	/*representation of the reservation to add
	  Required: true
	  In: body
	*/
	Reservation *models.Reservation
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostItemNameReservationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rName, rhkName, _ := route.Params.GetOK("name")
	if err := o.bindName(rName, rhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Reservation
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("reservation", "body"))
			} else {
				res = append(res, errors.NewParseError("reservation", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Reservation = &body
			}
		}

	} else {
		res = append(res, errors.Required("reservation", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostItemNameReservationParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Name = raw

	if err := o.validateName(formats); err != nil {
		return err
	}

	return nil
}

func (o *PostItemNameReservationParams) validateName(formats strfmt.Registry) error {

	if err := validate.MinLength("name", "path", string(o.Name), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "path", string(o.Name), 512); err != nil {
		return err
	}

	return nil
}
