package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/tompscanlan/labreserved/models"
)

/*PostItemOK Accepted

swagger:response postItemOK
*/
type PostItemOK struct {

	// In: body
	Payload *models.Item `json:"body,omitempty"`
}

// NewPostItemOK creates PostItemOK with default headers values
func NewPostItemOK() *PostItemOK {
	return &PostItemOK{}
}

// WithPayload adds the payload to the post item o k response
func (o *PostItemOK) WithPayload(payload *models.Item) *PostItemOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post item o k response
func (o *PostItemOK) SetPayload(payload *models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostItemOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostItemBadRequest Error

swagger:response postItemBadRequest
*/
type PostItemBadRequest struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewPostItemBadRequest creates PostItemBadRequest with default headers values
func NewPostItemBadRequest() *PostItemBadRequest {
	return &PostItemBadRequest{}
}

// WithPayload adds the payload to the post item bad request response
func (o *PostItemBadRequest) WithPayload(payload string) *PostItemBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post item bad request response
func (o *PostItemBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostItemBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
