package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/tompscanlan/labreserved/models"
)

// NewPostItemParams creates a new PostItemParams object
// with the default values initialized.
func NewPostItemParams() PostItemParams {
	var ()
	return PostItemParams{}
}

// PostItemParams contains all the bound params for the post item operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostItem
type PostItemParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*representation of the item to add
	  Required: true
	  In: body
	*/
	Additem *models.Item
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostItemParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Item
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("additem", "body"))
			} else {
				res = append(res, errors.NewParseError("additem", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Additem = &body
			}
		}

	} else {
		res = append(res, errors.Required("additem", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
