package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetItemNameParams creates a new GetItemNameParams object
// with the default values initialized.
func NewGetItemNameParams() *GetItemNameParams {
	var ()
	return &GetItemNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetItemNameParamsWithTimeout creates a new GetItemNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetItemNameParamsWithTimeout(timeout time.Duration) *GetItemNameParams {
	var ()
	return &GetItemNameParams{

		timeout: timeout,
	}
}

/*GetItemNameParams contains all the parameters to send to the API endpoint
for the get item name operation typically these are written to a http.Request
*/
type GetItemNameParams struct {

	/*Name
	  name of the lab equipment

	*/
	Name string

	timeout time.Duration
}

// WithName adds the name to the get item name params
func (o *GetItemNameParams) WithName(Name string) *GetItemNameParams {
	o.Name = Name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetItemNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
