package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/tompscanlan/labreserved/models"
)

// GetItemNameReader is a Reader for the GetItemName structure.
type GetItemNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetItemNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetItemNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetItemNameOK creates a GetItemNameOK with default headers values
func NewGetItemNameOK() *GetItemNameOK {
	return &GetItemNameOK{}
}

/*GetItemNameOK handles this case with default header values.

get specific lab item
*/
type GetItemNameOK struct {
	Payload *models.Item
}

func (o *GetItemNameOK) Error() string {
	return fmt.Sprintf("[GET /item/{name}][%d] getItemNameOK  %+v", 200, o.Payload)
}

func (o *GetItemNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Item)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
