package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetItemsParams creates a new GetItemsParams object
// with the default values initialized.
func NewGetItemsParams() *GetItemsParams {

	return &GetItemsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetItemsParamsWithTimeout creates a new GetItemsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetItemsParamsWithTimeout(timeout time.Duration) *GetItemsParams {

	return &GetItemsParams{

		timeout: timeout,
	}
}

/*GetItemsParams contains all the parameters to send to the API endpoint
for the get items operation typically these are written to a http.Request
*/
type GetItemsParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *GetItemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
