package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/tompscanlan/labreserved/models"
)

// NewPostItemParams creates a new PostItemParams object
// with the default values initialized.
func NewPostItemParams() *PostItemParams {
	var ()
	return &PostItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostItemParamsWithTimeout creates a new PostItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostItemParamsWithTimeout(timeout time.Duration) *PostItemParams {
	var ()
	return &PostItemParams{

		timeout: timeout,
	}
}

/*PostItemParams contains all the parameters to send to the API endpoint
for the post item operation typically these are written to a http.Request
*/
type PostItemParams struct {

	/*Additem
	  representation of the item to add

	*/
	Additem *models.Item

	timeout time.Duration
}

// WithAdditem adds the additem to the post item params
func (o *PostItemParams) WithAdditem(Additem *models.Item) *PostItemParams {
	o.Additem = Additem
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Additem == nil {
		o.Additem = new(models.Item)
	}

	if err := r.SetBodyParam(o.Additem); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
